/*

 BOARD_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 21

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __board_tiles_h_INCLUDE
#define __board_tiles_h_INCLUDE

/* Bank of tiles. */
#define board_tilesBank 0
/* Start of tile array. */
extern const unsigned char board_tiles[];

#endif

/* End of BOARD_TILES.H */
