/*

 TEST_TITLE_LAYOUT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Documents\gbdk\GBTD\testtitle.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __test_title_layout_h_INCLUDE
#define __test_title_layout_h_INCLUDE

#define test_title_layoutWidth 20
#define test_title_layoutHeight 18
#define test_title_layoutBank 0

extern const unsigned char test_title_layout[];

#endif

/* End of TEST_TITLE_LAYOUT.H */
