/*

 GAME_BOARD_LAYOUT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 19
   Tile set      : D:\Documents\gbdk\GBTD\hitoriboard.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __game_board_layout_h_INCLUDE
#define __game_board_layout_h_INCLUDE

#define board_layoutWidth 21
#define board_layoutHeight 19
#define board_layoutBank 0

extern const unsigned char board_layout[];

#define title_layoutWidth 20
#define title_layoutHeight 18
#define title_layoutBank 0

extern const unsigned char title_layout[];

#define title_tilesBank 0
extern const unsigned char title_tiles[];

#define board_tilesBank 0
extern const unsigned char board_tiles[];

#define cursor_tileBank 0
extern const unsigned char cursor_tile[];

#endif

/* End of GAME_BOARD_LAYOUT.H */
