/*

 TITLE_LAYOUT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_layout_h_INCLUDE
#define __title_layout_h_INCLUDE

#define title_layoutWidth 20
#define title_layoutHeight 18
#define title_layoutBank 0

extern const unsigned char title_layout[];

#endif

/* End of TITLE_LAYOUT.H */
